/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lector_Datos;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author utente
 */
public class Menu_Tablas extends javax.swing.JFrame {
    
    ArrayList<Tabla> baseTabla;
    /**
     * Creates new form Menu_Tablas
     * @param baseTabla
     */
    public Menu_Tablas(ArrayList<Tabla> baseTabla) {
        this.baseTabla = baseTabla;
        initComponents();
        llenarComboBox();
        obtenerModeloTabla(baseTabla.get(0).getNombreTabla());
    }
    
    private void llenarComboBox() {
        
        for (Tabla ta : baseTabla) {
            selectTablaComboBox.addItem(ta.getNombreTabla());
        }  
        
        selectTablaComboBox.setSelectedItem(0);
    }
    
    
    
    private void obtenerModeloTabla(String nombre){
 
        Tabla tabla = null;
        
        for (Tabla ta : baseTabla) {
            if (nombre.equals(ta.getNombreTabla())) {
                tabla = ta;
            }
        }
            
        DefaultTableModel modelo =new DefaultTableModel(); 

        String[] nombreColumnas = new String[tabla.getListaAtributos().size()];
        
        for (int i = 0 ; i < tabla.getListaAtributos().size() ; i++) {
            nombreColumnas[i] = tabla.getListaAtributos().get(i).getNombre();
        }
        
        modelo.setColumnIdentifiers(nombreColumnas);      
     
        try{

            Object[] fila = new Object[modelo.getColumnCount()];
            
            for (int i = 0 ; i < tabla.getListaAtributos().get(0).getListaValores().size() ; i++) { 
                
                for (int j = 0 ; j < modelo.getColumnCount() ; j++) {
                    
                    fila[j] = tabla.getListaAtributos().get(j).getListaValores().get(i);                    
                }
                modelo.addRow(fila);
                
            }

            tablaJTable.setModel(modelo); 
        }
        catch (Exception ex) {
            System.err.println("Ha ocurrido un error al leer la tabla");
        }  
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJTable = new javax.swing.JTable();
        selectTablaComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaJTable.setModel(new javax.swing.table.DefaultTableModel(baseTabla.get(0).getListaAtributos().get(0).getListaValores().size(), baseTabla.get(0).getListaAtributos().size())
        );
        jScrollPane1.setViewportView(tablaJTable);

        selectTablaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTablaComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectTablaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(selectTablaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectTablaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTablaComboBoxActionPerformed
        obtenerModeloTabla(selectTablaComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_selectTablaComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> selectTablaComboBox;
    private javax.swing.JTable tablaJTable;
    // End of variables declaration//GEN-END:variables
}
